delete from accounts where id>23;
delete from combo_lines;
delete from entities where id>9;
delete from inventories;
delete from `lines`;
delete from logs;
delete from movements;
delete from orders;
delete from payments;
delete from posts;
delete from price_group_names where id>2;
delete from price_groups;
insert into price_groups (id, price_group_name_id, entity_id) values(1,1,5), (2,2,5);
delete from prices;
delete from product_categories;
delete from products;
delete from requirements;
insert into roles_users(id, user_id, role_id) values(1,2,4), (2,2,7),(3,2,8),(4,2,10);
delete from roles_users where id>4;
delete from serialized_products;
delete from subscriptions;
delete from trans;
delete from units where id>7;
delete from users where id>2;
delete from warranties;
delete from costs;
delete from production_orders;
delete from production_order_lines;
