#! /bin/bash
set -e
function install_ruby {
	echo "          | Installing Ruby                                     |"
	sudo apt-get install ruby-full build-essential
}
function install_apache {
	echo "          | Installing Apache 2 Server with development headers |"
	sudo apt-get install apache2 apache2-prefork-dev libapr1-dev libaprutil1-dev
}
function install_gem {
	echo "          | Installing Ruby Gem 1.3.1                           |"
	wget http://rubyforge.org/frs/download.php/45905/rubygems-1.3.1.tgz
	tar xzvf rubygems-1.3.1.tgz
	cd rubygems-1.3.1
	sudo ruby setup.rb
	sudo ln -s /usr/bin/gem1.8 /usr/bin/gem
	sudo gem update --system
}

function install_rails {
	echo "          | Installing Rails                                    |"
	sudo gem install rails
}
function install_passenger {
	echo "          | Installing Passenger                                |"
	sudo gem install passenger
	sudo passenger-install-apache2-module
	echo "
	LoadModule passenger_module /usr/lib/ruby/gems/1.8/gems/passenger-2.2.8/ext/apache2/mod_passenger.so
		 PassengerRoot /usr/lib/ruby/gems/1.8/gems/passenger-2.2.8
		 PassengerRuby /usr/bin/ruby1.8
	" | sudo tee -a /etc/apache2/apache2.conf
	echo "
	NameVirtualHost *
	<VirtualHost *>
		    ServerName jade.local
		    DocumentRoot /srv/jade/public
		    RailsEnv production
		 </VirtualHost>
	" > /etc/apache2/sites-enabled/000-default
}
function install_gems {
	echo "          | Installing gems needed by Jade:                     |
          | Prawn and Will_Paginate                             |"
	sudo gem install prawn
	sudo gem install will_paginate
}
function install_barcodes {
	echo "          | Installing utilities to make barcodes               |"
	sudo apt-get install barcode imagemagick gs
}
function install_dbconfig {
	echo "          | Copying default configuration                       |"
	sudo cp database.yml.sample config/database.yml
}
function install_mysql {
	echo "          | Installing MYSQL Server                             |"
	sudo apt-get install mysql-server mysql-client
	sudo apt-get install libmysql-ruby libmysqlclient15-dev
	sudo gem install mysql
}
function install_db {
	echo "          | Installing initial database                         |"
	sudo mysql -p -f < base_data.sql
}
function show_help {
	echo "          | call this script with one of the options below      |
          |                                                     |
          | all ------- Installs all of the components          |
          | ruby ------ Installs ruby 1.3.1                     |
          | apache ---- Installs Apache Web Server 2            |
          | gem ------- Installs Ruby Gem                       |
          | rails ----- Installs Rails                          |
          | passenger - Installs Passenger and configures       | 
          |             itself in Apache                        |
          | gems ------ Installs the gems used by Jade:         |
          |             Prawn and will_paginate                 |
          | barcodes -- Installs utilities used to create       |
          |             barcodes                                |
          | dbconfig -- Copies default database.yml for Jade    |
          | mysql ----- Installs MYSQL database server          |
          | db -------- Creates default databases for Jade      |
          |=====================================================|"
}
echo "
          |=====================================================|
          | Jade installer script for for Ubuntu 8.04 Server    |
          |=====================================================|"
for var in "$@"
do
	case $var in
	"ruby" )
		install_ruby;;
	"apache" )
		install_apache;;
	"gem" )
		install_gem;;
	"rails" )
		install_rails;;
	"passenger" )
		install_passenger;;
	"gems" )
		install_gems;;
	"barcodes" )
		install_barcodes;;
	"dbconfig" )
		install_dbconfig;;
	"mysql" )
		install_mysql;;
	"db" )
		install_db;;
	"all" )
		install_ruby
		install_apache
		install_gem
		install_rails
		install_passenger
		install_gems
		install_barcodes
		install_dbconfig
		install_mysql
		install_db;;
	"help" )
		show_help;;
	"--help" )
		show_help;;
	"-h" )
		show_help;;
	esac
done
echo "          |=====================================================|
          | Finished Installing Requested Components            |
          |=====================================================|"


