class User < ActiveRecord::Base
end
class Account < ActiveRecord::Base
end
class EntityType < ActiveRecord::Base
end
class State < ActiveRecord::Base
end
class MovementType < ActiveRecord::Base
end
class OrderType < ActiveRecord::Base
end
class Preference < ActiveRecord::Base
end
class PaymentMethod < ActiveRecord::Base
end
class PostType < ActiveRecord::Base
end
class PriceGroup < ActiveRecord::Base
end
class PriceGroupName < ActiveRecord::Base
end
class ProductType < ActiveRecord::Base
end
class Right < ActiveRecord::Base
end
class Entity < ActiveRecord::Base
end
o=Entity.new(:id=>1, :name=>'Consumo Interno', :entity_type_id=>0, :state_id=>12, :active=>1, :site_id=>5)
o.id=1; o.save;o=Entity.new(:id=>2, :name=>'Varios', :entity_type_id=>1, :cash_account_id=>14, :state_id=>12, :active=>1, :site_id=>5)
o.id=2; o.save;o=Entity.new(:id=>3, :name=>'Anonimo', :entity_type_id=>2, :price_group_id=>1, :price_group_name_id=>1, :site_id=>5, :cash_account_id=>1, :state_id=>12, :active=>1, :site_id=>5)
o.id=3; o.save;o=Entity.new(:id=>4, :name=>'No Specificado', :entity_type_id=>1, :cash_account_id=>14, :state_id=>12, :active=>1, :site_id=>5)
o.id=4; o.save;o=Entity.new(:id=>5, :name=>'Principal', :entity_type_id=>3, :state_id=>12, :active=>1, :price_group_id=> 1, :inventory_account_id=> 20, :cash_account_id=> 16, :revenue_account_id=>18, :expense_account_id=>17, :tax_account_id => 19, :next_receipt_number=> "1", :client_accounts_group_id=>23, :vendor_accounts_group_id=> 21, :next_bar_code=>"1001", :site_id=>5)
o.id=5; o.save;o=Entity.new(:id=>9, :name=>'Anulado', :entity_type_id=>2, :state_id=>12, :active=>1, :site_id=>5)
o.id=9; o.save;o=User.new(:id=>1, :name=>'Sistema Jade', :login=>'Sistema Jade', :location_id=> 5, :price_group_name_id=> 1, :do_accounting=>1)
o.id=1; o.save;User.current_user=o
o=User.new(:id=>2, :name=>'Administrador', :login=>'admin', :crypted_password=>"be82f10808d1870ce15d4a47fba42173beb748e9", :location_id=> 5, :price_group_name_id=> 1, :do_accounting=>1)
o.id=2; o.save;o=Account.new(:id=>1, :name=>"Clientes Anonimos", :parent_id=>15, :entity_id=>3, :number=>"14101", :modifier=>1, :is_parent=>0)
o.id=1; o.save;o=Account.new(:id=>2, :name=>"Activos", :parent_id=>nil, :entity_id=>nil, :number=>"1", :modifier=>1, :is_parent=>1)
o.id=2; o.save;o=Account.new(:id=>3, :name=>"Pasivos", :parent_id=>nil, :entity_id=>nil, :number=>"2", :modifier=>-1, :is_parent=>1)
o.id=3; o.save;o=Account.new(:id=>4, :name=>"Patrimonio", :parent_id=>nil, :entity_id=>nil, :number=>"3", :modifier=>-1, :is_parent=>0)
o.id=4; o.save;o=Account.new(:id=>5, :name=>"Ingresos", :parent_id=>nil, :entity_id=>nil, :number=>"4", :modifier=>-1, :is_parent=>1)
o.id=5; o.save;o=Account.new(:id=>6, :name=>"Gastos", :parent_id=>nil, :entity_id=>nil, :number=>"5", :modifier=>1, :is_parent=>1)
o.id=6; o.save;o=Account.new(:id=>7, :name=>"Efectivo", :parent_id=>2, :entity_id=>nil, :number=>"11", :modifier=>1, :is_parent=>1)
o.id=7; o.save;o=Account.new(:id=>8, :name=>"Inventario", :parent_id=>2, :entity_id=>nil, :number=>"12", :modifier=>1, :is_parent=>1)
o.id=8; o.save;o=Account.new(:id=>9, :name=>"Cuenta Bancaria", :parent_id=>2, :entity_id=>nil, :number=>"13", :modifier=>1, :is_parent=>0)
o.id=9; o.save;o=Account.new(:id=>10, :name=>"Cuentas a Cobrar", :parent_id=>2, :entity_id=>nil, :number=>"14", :modifier=>1, :is_parent=>1)
o.id=10; o.save;o=Account.new(:id=>11, :name=>"Cuentas por Pagar", :parent_id=>3, :entity_id=>nil, :number=>"21", :modifier=>-1, :is_parent=>1)
o.id=11; o.save;o=Account.new(:id=>12, :name=>"Impuesto", :parent_id=>3, :entity_id=>nil, :number=>"22", :modifier=>-1, :is_parent=>1)
o.id=12; o.save;o=Account.new(:id=>13, :name=>"Empleados", :parent_id=>11, :entity_id=>nil, :number=>"211", :modifier=>-1, :is_parent=>1)
o.id=13; o.save;o=Account.new(:id=>14, :name=>"Proveedores", :parent_id=>11, :entity_id=>nil, :number=>"212", :modifier=>-1, :is_parent=>1)
o.id=14; o.save;o=Account.new(:id=>15, :name=>"Clientes", :parent_id=>10, :entity_id=>nil, :number=>"141", :modifier=>1, :is_parent=>1)
o.id=15; o.save;o=Account.new(:id=>16, :name=>"Efectivo en Principal", :parent_id=>7, :entity_id=>5, :number=>"1101", :modifier=>1, :is_parent=>0)
o.id=16; o.save;o=Account.new(:id=>17, :name=>"Gastos en Principal", :parent_id=>6, :entity_id=>5, :number=>"501", :modifier=>1, :is_parent=>0)
o.id=17; o.save;o=Account.new(:id=>18, :name=>"Ingresos en Principal", :parent_id=>5, :entity_id=>5, :number=>"401", :modifier=>-1, :is_parent=>0)
o.id=18; o.save;o=Account.new(:id=>19, :name=>"Impuestos en Principal", :parent_id=>12, :entity_id=>5, :number=>"2201", :modifier=>-1, :is_parent=>0)
o.id=19; o.save;o=Account.new(:id=>20, :name=>"Inventario en Principal", :parent_id=>8, :entity_id=>5, :number=>"1201", :modifier=>1, :is_parent=>0)
o.id=20; o.save;o=Account.new(:id=>21, :name=>"Principal Proveedores", :parent_id=>14, :entity_id=>nil, :number=>"21201", :modifier=>-1, :is_parent=>1)
o.id=21; o.save;o=Account.new(:id=>22, :name=>"Principal Empleados", :parent_id=>13, :entity_id=>nil, :number=>"21101", :modifier=>-1, :is_parent=>1)
o.id=22; o.save;o=Account.new(:id=>23, :name=>"Principal Clientes", :parent_id=>15, :entity_id=>nil, :number=>"14102", :modifier=>1, :is_parent=>1)
o.id=23; o.save;o=EntityType.new(:id=>1, :name=>"Proveedor")
o.id=1; o.save;o=EntityType.new(:id=>2, :name=>"Consumidor Final")
o.id=2; o.save;o=EntityType.new(:id=>3, :name=>"Sitio")
o.id=3; o.save;o=EntityType.new(:id=>5, :name=>"Credito Fiscal")
o.id=5; o.save;o=EntityType.new(:id=>6, :name=>"Empleado")
o.id=6; o.save;o=EntityType.new(:id=>7, :name=>"Cuenta Bancaria")
o.id=7; o.save;o=State.new(:id=>1, :name=>'Ahuachapán')
o.id=1; o.save;o=State.new(:id=>14, :name=>'Usulután')
o.id=14; o.save;o=State.new(:id=>13, :name=>'Sonsonate')
o.id=13; o.save;o=State.new(:id=>11, :name=>'San Vicente')
o.id=11; o.save;o=State.new(:id=>12, :name=>'Santa Ana')
o.id=12; o.save;o=State.new(:id=>10, :name=>'San Salvador')
o.id=10; o.save;o=State.new(:id=>9, :name=>'San Miguel')
o.id=9; o.save;o=State.new(:id=>8, :name=>'Morazán')
o.id=8; o.save;o=State.new(:id=>7, :name=>'La Unión')
o.id=7; o.save;o=State.new(:id=>5, :name=>'La Libertad')
o.id=5; o.save;o=State.new(:id=>6, :name=>'La Paz')
o.id=6; o.save;o=State.new(:id=>4, :name=>'Cuscatlán')
o.id=4; o.save;o=State.new(:id=>3, :name=>'Chalatenango')
o.id=3; o.save;o=State.new(:id=>2, :name=>'Cabañas')
o.id=2; o.save;o=MovementType.new(:id=>1, :name=>"Venta")
o.id=1; o.save;o=MovementType.new(:id=>2, :name=>"Compra")
o.id=2; o.save;o=MovementType.new(:id=>3, :name=>"Transferencia")
o.id=3; o.save;o=MovementType.new(:id=>4, :name=>"Cuenta Fisica")
o.id=4; o.save;o=MovementType.new(:id=>5, :name=>"Devolucion de Venta")
o.id=5; o.save;o=MovementType.new(:id=>6, :name=>"Devolucion de Compra")
o.id=6; o.save;o=MovementType.new(:id=>7, :name=>"Devolucion de Transferencia")
o.id=7; o.save;o=MovementType.new(:id=>8, :name=>"Consumo Interno")
o.id=8; o.save;o=MovementType.new(:id=>9, :name=>"Devolucion de Consumo Interno")
o.id=9; o.save;o=MovementType.new(:id=>10, :name=>"Pago")
o.id=10; o.save;o=MovementType.new(:id=>11, :name=>"Deposito")
o.id=11; o.save;o=MovementType.new(:id=>12, :name=>"Retiro")
o.id=12; o.save;o=MovementType.new(:id=>13, :name=>"Pago")
o.id=13; o.save;o=MovementType.new(:id=>14, :name=>"Deposito")
o.id=14; o.save;o=MovementType.new(:id=>15, :name=>"Retiro")
o.id=15; o.save;o=OrderType.new(:id=>1, :name=>"Venta")
o.id=1; o.save;o=OrderType.new(:id=>2, :name=>"Compra")
o.id=2; o.save;o=OrderType.new(:id=>3, :name=>"Consumo Interno")
o.id=3; o.save;o=OrderType.new(:id=>4, :name=>"Transferencia")
o.id=4; o.save;o=OrderType.new(:id=>5, :name=>"Cuenta Fisica")
o.id=5; o.save;o=OrderType.new(:id=>6, :name=>"Abono a cuenta")
o.id=6; o.save;o=OrderType.new(:id=>7, :name=>"Transferencia de Fondos")
o.id=7; o.save;o=PaymentMethod.new(:id=>1, :name=>"Efectivo")
o.id=1; o.save;o=PaymentMethod.new(:id=>2, :name=>"Cheque")
o.id=2; o.save;o=PaymentMethod.new(:id=>3, :name=>"Tarjeta de Credito")
o.id=3; o.save;o=PaymentMethod.new(:id=>4, :name=>"Credito")
o.id=4; o.save;o=PostType.new(:id=>1, :name=>"Debito")
o.id=1; o.save;o=PostType.new(:id=>-1, :name=>"Credito")
o.id=-1; o.save;o=Preference.new(:id=>1, :name=>"Producto", :value=>1, :pref_group=>"revenue")
o.id=1; o.save;o=Preference.new(:id=>2, :name=>"Categoria", :value=>2, :pref_group=>"revenue")
o.id=2; o.save;o=Preference.new(:id=>3, :name=>"Proveedor", :value=>3, :pref_group=>"revenue")
o.id=3; o.save;o=Preference.new(:id=>4, :name=>"Sitio", :value=>5, :pref_group=>"revenue")
o.id=4; o.save;o=Preference.new(:id=>5, :name=>"Asesor", :value=>4, :pref_group=>"revenue")
o.id=5; o.save;o=Preference.new(:id=>6, :name=>"Usuario", :value=>6, :pref_group=>"revenue")
o.id=6; o.save;o=Preference.new(:id=>7, :name=>"Sitio", :value=>4, :pref_group=>"cash")
o.id=7; o.save;o=Preference.new(:id=>8, :name=>"Asesor", :value=>2, :pref_group=>"cash")
o.id=8; o.save;o=Preference.new(:id=>9, :name=>"Usuario", :value=>3, :pref_group=>"cash")
o.id=9; o.save;o=PriceGroupName.new(:id=>1, :name=>"Publico")
o.id=1; o.save;o=PriceGroupName.new(:id=>2, :name=>"Mayoreo")
o.id=2; o.save;o=PriceGroup.new(:id=>1, :price_group_name_id=>1, :entity_id=>5)
o.id=1; o.save;o=PriceGroup.new(:id=>2, :price_group_name_id=>2, :entity_id=>5)
o.id=2; o.save;o=ProductType.new(:id=>1, :name=>"Simple")
o.id=1; o.save;o=ProductType.new(:id=>2, :name=>"Discount")
o.id=2; o.save;o=ProductType.new(:id=>3, :name=>"Combo")
o.id=3; o.save;o=ProductType.new(:id=>4, :name=>"Service")
o.id=4; o.save;o=Right.new(:id=>1, :name=>"Crear Pagos para Ventas")
o.id=1; o.save;o=Right.new(:id=>2, :name=>"Cambiar Pagos para Ventas")
o.id=2; o.save;o=Right.new(:id=>3, :name=>"Ver Pagos para Ventas")
o.id=3; o.save;o=Right.new(:id=>4, :name=>"Borrar Pagos para Ventas")
o.id=4; o.save;o=Right.new(:id=>5, :name=>"Crear Pagos para Compras")
o.id=5; o.save;o=Right.new(:id=>6, :name=>"Cambiar Pagos para Compras")
o.id=6; o.save;o=Right.new(:id=>7, :name=>"Ver Pagos para Compras")
o.id=7; o.save;o=Right.new(:id=>8, :name=>"Borrar Pagos para Compras")
o.id=8; o.save;o=Right.new(:id=>9, :name=>"Crear Ventas")
o.id=9; o.save;o=Right.new(:id=>10, :name=>"Cambiar Ventas")
o.id=10; o.save;o=Right.new(:id=>11, :name=>"Ver Ventas")
o.id=11; o.save;o=Right.new(:id=>12, :name=>"Borrar Ventas")
o.id=12; o.save;o=Right.new(:id=>13, :name=>"Crear Compras")
o.id=13; o.save;o=Right.new(:id=>14, :name=>"Cambiar Compras")
o.id=14; o.save;o=Right.new(:id=>15, :name=>"Ver Compras")
o.id=15; o.save;o=Right.new(:id=>16, :name=>"Borrar Compras")
o.id=16; o.save;o=Right.new(:id=>17, :name=>"Crear Consumidor Final")
o.id=17; o.save;o=Right.new(:id=>18, :name=>"Cambiar Consumidor Final")
o.id=18; o.save;o=Right.new(:id=>19, :name=>"Ver Consumidor Final")
o.id=19; o.save;o=Right.new(:id=>20, :name=>"Borrar Consumidor Final")
o.id=20; o.save;o=Right.new(:id=>21, :name=>"Crear Credito Fiscal")
o.id=21; o.save;o=Right.new(:id=>22, :name=>"Cambiar Credito Fiscal")
o.id=22; o.save;o=Right.new(:id=>23, :name=>"Ver Credito Fiscal")
o.id=23; o.save;o=Right.new(:id=>24, :name=>"Borrar Credito Fiscal")
o.id=24; o.save;o=Right.new(:id=>25, :name=>"Crear Productos")
o.id=25; o.save;o=Right.new(:id=>26, :name=>"Cambiar Productos")
o.id=26; o.save;o=Right.new(:id=>27, :name=>"Ver Productos")
o.id=27; o.save;o=Right.new(:id=>28, :name=>"Borrar Productos")
o.id=28; o.save;o=Right.new(:id=>29, :name=>"Crear Suscripciones")
o.id=29; o.save;o=Right.new(:id=>30, :name=>"Cambiar Suscripciones")
o.id=30; o.save;o=Right.new(:id=>31, :name=>"Ver Suscripciones")
o.id=31; o.save;o=Right.new(:id=>32, :name=>"Borrar Suscripciones")
o.id=32; o.save;o=Right.new(:id=>33, :name=>"Crear Papeles")
o.id=33; o.save;o=Right.new(:id=>34, :name=>"Cambiar Papeles")
o.id=34; o.save;o=Right.new(:id=>35, :name=>"Ver Papeles")
o.id=35; o.save;o=Right.new(:id=>36, :name=>"Borrar Papeles")
o.id=36; o.save;o=Right.new(:id=>37, :name=>"Crear Usuarios")
o.id=37; o.save;o=Right.new(:id=>38, :name=>"Cambiar Usuarios")
o.id=38; o.save;o=Right.new(:id=>39, :name=>"Ver Usuarios")
o.id=39; o.save;o=Right.new(:id=>40, :name=>"Borrar Usuarios")
o.id=40; o.save;o=Right.new(:id=>41, :name=>"Crear Sitios")
o.id=41; o.save;o=Right.new(:id=>42, :name=>"Cambiar Sitios")
o.id=42; o.save;o=Right.new(:id=>43, :name=>"Ver Sitios")
o.id=43; o.save;o=Right.new(:id=>44, :name=>"Borrar Sitios")
o.id=44; o.save;o=Right.new(:id=>45, :name=>"Crear Cuentas Fisicas")
o.id=45; o.save;o=Right.new(:id=>46, :name=>"Cambiar Cuentas Fisicas")
o.id=46; o.save;o=Right.new(:id=>47, :name=>"Ver Cuentas Fisicas")
o.id=47; o.save;o=Right.new(:id=>48, :name=>"Borrar Cuentas Fisicas")
o.id=48; o.save;o=Right.new(:id=>49, :name=>"Ver COSTS")
o.id=49; o.save;o=Right.new(:id=>50, :name=>"Crear Cuentas")
o.id=50; o.save;o=Right.new(:id=>51, :name=>"Cambiar Cuentas")
o.id=51; o.save;o=Right.new(:id=>52, :name=>"Ver Cuentas")
o.id=52; o.save;o=Right.new(:id=>53, :name=>"Borrar Cuentas")
o.id=53; o.save;o=Right.new(:id=>54, :name=>"Crear Servicios")
o.id=54; o.save;o=Right.new(:id=>55, :name=>"Cambiar Servicios")
o.id=55; o.save;o=Right.new(:id=>56, :name=>"Ver Servicios")
o.id=56; o.save;o=Right.new(:id=>57, :name=>"Borrar Servicios")
o.id=57; o.save;o=Right.new(:id=>58, :name=>"Crear Combos")
o.id=58; o.save;o=Right.new(:id=>59, :name=>"Cambiar Combos")
o.id=59; o.save;o=Right.new(:id=>60, :name=>"Ver Combos")
o.id=60; o.save;o=Right.new(:id=>61, :name=>"Borrar Combos")
o.id=61; o.save;o=Right.new(:id=>62, :name=>"Crear Descuentos")
o.id=62; o.save;o=Right.new(:id=>63, :name=>"Cambiar Descuentos")
o.id=63; o.save;o=Right.new(:id=>64, :name=>"Ver Descuentos")
o.id=64; o.save;o=Right.new(:id=>65, :name=>"Borrar Descuentos")
o.id=65; o.save;o=Right.new(:id=>66, :name=>"Crear Garantias")
o.id=66; o.save;o=Right.new(:id=>67, :name=>"Cambiar Garantias")
o.id=67; o.save;o=Right.new(:id=>68, :name=>"Ver Garantias")
o.id=68; o.save;o=Right.new(:id=>69, :name=>"Borrar Garantias")
o.id=69; o.save;o=Right.new(:id=>70, :name=>"Crear Consumos Internos")
o.id=70; o.save;o=Right.new(:id=>71, :name=>"Cambiar Consumos Internos")
o.id=71; o.save;o=Right.new(:id=>72, :name=>"Ver Consumos Internos")
o.id=72; o.save;o=Right.new(:id=>73, :name=>"Borrar Consumos Internos")
o.id=73; o.save;o=Right.new(:id=>74, :name=>"Crear Numeros de Serie")
o.id=74; o.save;o=Right.new(:id=>75, :name=>"Cambiar Numeros de Serie")
o.id=75; o.save;o=Right.new(:id=>76, :name=>"Ver Numeros de Serie")
o.id=76; o.save;o=Right.new(:id=>77, :name=>"Borrar Numeros de Serie")
o.id=77; o.save;o=Right.new(:id=>78, :name=>"Cambiar Prices")
o.id=78; o.save;o=Right.new(:id=>79, :name=>"Crear Proveedores")
o.id=79; o.save;o=Right.new(:id=>80, :name=>"Cambiar Proveedores")
o.id=80; o.save;o=Right.new(:id=>81, :name=>"Ver Proveedores")
o.id=81; o.save;o=Right.new(:id=>82, :name=>"Borrar Proveedores")
o.id=82; o.save;o=Right.new(:id=>83, :name=>"Crear Transacciones")
o.id=83; o.save;o=Right.new(:id=>84, :name=>"Cambiar Transacciones")
o.id=84; o.save;o=Right.new(:id=>85, :name=>"Ver Transacciones")
o.id=85; o.save;o=Right.new(:id=>86, :name=>"Borrar Transacciones")
o.id=86; o.save;o=Right.new(:id=>87, :name=>"Procesar Cuentas Fisicas")
o.id=87; o.save;o=Right.new(:id=>88, :name=>"Crear Ordenes de Produccion")
o.id=88; o.save;o=Right.new(:id=>89, :name=>"Cambiar Ordenes de Produccion")
o.id=89; o.save;o=Right.new(:id=>90, :name=>"Ver Ordenes de Produccion")
o.id=90; o.save;o=Right.new(:id=>91, :name=>"Borrar Ordenes de Produccion")
o.id=91; o.save;o=Right.new(:id=>92, :name=>"Crear Procesos de Produccion")
o.id=92; o.save;o=Right.new(:id=>93, :name=>"Cambiar Procesos de Produccion")
o.id=93; o.save;o=Right.new(:id=>94, :name=>"Ver Procesos de Produccion")
o.id=94; o.save;o=Right.new(:id=>95, :name=>"Borrar Procesos de Produccion")
o.id=95; o.save;o=Right.new(:id=>96, :name=>"Iniciar Ordenes de Produccion")
o.id=96; o.save;o=Right.new(:id=>97, :name=>"Terminar Ordenes de Produccion")
o.id=97; o.save
