ahuachapan==State.create(:id=>1, :name=>'Ahuachapán')
usulutan=State.create(:id=>14, :name=>'Usulután')
sonsonate=State.create(:id=>13, :name=>'Sonsonate')
san_vicente=State.create(:id=>11, :name=>'San Vicente')
santa_ana=State.create(:id=>12, :name=>'Santa Ana')
san_salvador=State.create(:id=>10, :name=>'San Salvador')
san_miguel=State.create(:id=>9, :name=>'San Miguel')
morazan=State.create(:id=>8, :name=>'Morazán')
la_union=State.create(:id=>7, :name=>'La Unión')
la_libertad=State.create(:id=>5, :name=>'La Libertad')
la_paz=State.create(:id=>6, :name=>'La Paz')
cuscatlan=State.create(:id=>4, :name=>'Cuscatlán')
chalatenango=State.create(:id=>3, :name=>'Chalatenango')
cabanas=State.create(:id=>2, :name=>'Cabañas')

home=Entity.create(:id=>5, :name=>'Principal', :entity_type_id=>3, :state => santa_ana, :active=>1, :next_receipt_number=> "1", :next_bar_code=>"1001", :site=>home)
consumo=Entity.create(:id=>1, :name=>'Consumo Interno', :entity_type_id=>0, :state => santa_ana, :active=>1, :site=>home)
varios=Entity.create(:id=>2, :name=>'Varios', :entity_type_id=>1, :cash_account_id=>14, :state => santa_ana, :active=>1, :site=>home)
anonimo=Entity.create(:id=>3, :name=>'Anonimo', :entity_type_id=>2, :price_group_id=>1, :price_group_name_id=>1, :site=>home, :cash_account_id=>1, :state => santa_ana, :active=>1, :site=>home)
no_specificado=Entity.create(:id=>4, :name=>'No Specificado', :entity_type_id=>1, :cash_account_id=>14, :state => santa_ana, :active=>1, :site=>home)
anulado=Entity.create(:id=>9, :name=>'Anulado', :entity_type_id=>2, :state => santa_ana, :active=>1, :site=>home)

publico=PriceGroupName.create(:id=>1, :name=>"Publico")
mayoreo=PriceGroupName.create(:id=>2, :name=>"Mayoreo")
publico_group=PriceGroup.create(:id=>1, :price_group_name=>publico, :entity=>home)
mayoreo_group=PriceGroup.create(:id=>2, :price_group_name=>mayoreo, :entity=>home)

u1=User.create(:id=>1, :name=>'Sistema Jade', :login=>'Sistema Jade', :location_id=> 5, :price_group_name_id=> 1, :do_accounting=>1)
u2=User.create(:id=>2, :name=>'Administrador', :login=>'admin', :crypted_password=>"be82f10808d1870ce15d4a47fba42173beb748e9", :location_id=> 5, :price_group_name_id=> 1, :do_accounting=>1)

account_anonimo=Account.create(:id=>1, :name=>"Clientes Anonimos", :parent_id=>15, :entity_id=>3, :number=>"14101", :modifier=>1, :is_parent=>0)
account_activos=Account.create(:id=>2, :name=>"Activos", :parent_id=>nil, :entity_id=>nil, :number=>"1", :modifier=>1, :is_parent=>1)
account_pasivos=Account.create(:id=>3, :name=>"Pasivos", :parent_id=>nil, :entity_id=>nil, :number=>"2", :modifier=>-1, :is_parent=>1)
account_patrimonio=Account.create(:id=>4, :name=>"Patrimonio", :parent_id=>nil, :entity_id=>nil, :number=>"3", :modifier=>-1, :is_parent=>0)
account_ingresos=Account.create(:id=>5, :name=>"Ingresos", :parent_id=>nil, :entity_id=>nil, :number=>"4", :modifier=>-1, :is_parent=>1)
account_gastos=Account.create(:id=>6, :name=>"Gastos", :parent_id=>nil, :entity_id=>nil, :number=>"5", :modifier=>1, :is_parent=>1)
account_efectivo=Account.create(:id=>7, :name=>"Efectivo", :parent_id=>2, :entity_id=>nil, :number=>"11", :modifier=>1, :is_parent=>1)
account_inventario=Account.create(:id=>8, :name=>"Inventario", :parent_id=>2, :entity_id=>nil, :number=>"12", :modifier=>1, :is_parent=>1)
account_banco=Account.create(:id=>9, :name=>"Cuenta Bancaria", :parent_id=>2, :entity_id=>nil, :number=>"13", :modifier=>1, :is_parent=>0)
account_cobrar=Account.create(:id=>10, :name=>"Cuentas a Cobrar", :parent_id=>2, :entity_id=>nil, :number=>"14", :modifier=>1, :is_parent=>1)
account_pagar=Account.create(:id=>11, :name=>"Cuentas por Pagar", :parent_id=>3, :entity_id=>nil, :number=>"21", :modifier=>-1, :is_parent=>1)
account_impuesto=Account.create(:id=>12, :name=>"Impuesto", :parent_id=>3, :entity_id=>nil, :number=>"22", :modifier=>-1, :is_parent=>1)
account_empleados=Account.create(:id=>13, :name=>"Empleados", :parent_id=>11, :entity_id=>nil, :number=>"211", :modifier=>-1, :is_parent=>1)
account_proveedores=Account.create(:id=>14, :name=>"Proveedores", :parent_id=>11, :entity_id=>nil, :number=>"212", :modifier=>-1, :is_parent=>1)
account_clientes=Account.create(:id=>15, :name=>"Clientes", :parent_id=>10, :entity_id=>nil, :number=>"141", :modifier=>1, :is_parent=>1)
account_efectivo_principal=Account.create(:id=>16, :name=>"Efectivo en Principal", :parent_id=>7, :entity=>home, :number=>"1101", :modifier=>1, :is_parent=>0)
account_gastos_principal=Account.create(:id=>17, :name=>"Gastos en Principal", :parent_id=>6, :entity=>home, :number=>"501", :modifier=>1, :is_parent=>0)
account_ingresos_principal=Account.create(:id=>18, :name=>"Ingresos en Principal", :parent_id=>5, :entity=>home, :number=>"401", :modifier=>-1, :is_parent=>0)
account_impuestos_principal=Account.create(:id=>19, :name=>"Impuestos en Principal", :parent_id=>12, :entity=>home, :number=>"2201", :modifier=>-1, :is_parent=>0)
account_inventario_principal=Account.create(:id=>20, :name=>"Inventario en Principal", :parent_id=>8, :entity=>home, :number=>"1201", :modifier=>1, :is_parent=>0)
account_proveedores_principal=Account.create(:id=>21, :name=>"Principal Proveedores", :parent_id=>14, :entity_id=>nil, :number=>"21201", :modifier=>-1, :is_parent=>1)
account_empleados_principal=Account.create(:id=>22, :name=>"Principal Empleados", :parent_id=>13, :entity_id=>nil, :number=>"21101", :modifier=>-1, :is_parent=>1)
account_clientes_principal=Account.create(:id=>23, :name=>"Principal Clientes", :parent_id=>15, :entity_id=>nil, :number=>"14102", :modifier=>1, :is_parent=>1)

home.attributes={:price_group=publico_group, :inventory_account=> account_inventario_principal, :cash_account=> account_efectivo_principal, :revenue_account=>account_ingresos_principal, :expense_account=>account_gastos_principal, :tax_account_id => account_impuestos_principal, :client_accounts_group_id=>account_clientes_principal, :vendor_accounts_group_id=> account_proveedores_principal}
home.save

movement_venta=movement_=MovementType.create(:id=>1, :name=>"Venta")
movement_compra=MovementType.create(:id=>2, :name=>"Compra")
movement_tranferencia=MovementType.create(:id=>3, :name=>"Transferencia")
movement_cuenta_fisica=MovementType.create(:id=>4, :name=>"Cuenta Fisica")
movement_devolucion_de_venta=MovementType.create(:id=>5, :name=>"Devolucion de Venta")
movement_devolucion_de_compra=MovementType.create(:id=>6, :name=>"Devolucion de Compra")
movement_devolucion_de_transferencia=MovementType.create(:id=>7, :name=>"Devolucion de Transferencia")
movement_consumo_interno=MovementType.create(:id=>8, :name=>"Consumo Interno")
movement_devolucion_de_consumo_interno=MovementType.create(:id=>9, :name=>"Devolucion de Consumo Interno")
movement_pago=MovementType.create(:id=>10, :name=>"Pago")
movement_deposito=MovementType.create(:id=>11, :name=>"Deposito")
movement_retiro=MovementType.create(:id=>12, :name=>"Retiro")
venta=OrderType.create(:id=>1, :name=>"Venta")
compra=OrderType.create(:id=>2, :name=>"Compra")
consumo_interno=OrderType.create(:id=>3, :name=>"Consumo Interno")
transferencia=OrderType.create(:id=>4, :name=>"Transferencia")
cuenta_fisica=OrderType.create(:id=>5, :name=>"Cuenta Fisica")
abono=OrderType.create(:id=>6, :name=>"Abono a cuenta")
transferencia_de_fondos=OrderType.create(:id=>7, :name=>"Transferencia de Fondos")
pay_efectivo=PaymentMethod.create(:id=>1, :name=>"Efectivo")
PaymentMethod.create(:id=>2, :name=>"Cheque")
PaymentMethod.create(:id=>3, :name=>"Tarjeta de Credito")
PaymentMethod.create(:id=>4, :name=>"Credito")
credito=PostType.create(:id=>1, :name=>"Debito")
debito=PostType.create(:id=>-1, :name=>"Credito")
Preference.create(:id=>1, :name=>"Producto", :value=>1, :pref_group=>"revenue")
Preference.create(:id=>2, :name=>"Categoria", :value=>2, :pref_group=>"revenue")
Preference.create(:id=>3, :name=>"Proveedor", :value=>3, :pref_group=>"revenue")
Preference.create(:id=>4, :name=>"Sitio", :value=>5, :pref_group=>"revenue")
Preference.create(:id=>5, :name=>"Asesor", :value=>4, :pref_group=>"revenue")
Preference.create(:id=>6, :name=>"Usuario", :value=>6, :pref_group=>"revenue")
Preference.create(:id=>7, :name=>"Sitio", :value=>4, :pref_group=>"cash")
Preference.create(:id=>8, :name=>"Asesor", :value=>2, :pref_group=>"cash")
Preference.create(:id=>9, :name=>"Usuario", :value=>3, :pref_group=>"cash")

Product.create(:id=>1, :name=>"Simple")
Product.create(:id=>2, :name=>"Discount")
Product.create(:id=>3, :name=>"Combo")
Product.create(:id=>4, :name=>"Service")

Right.create(:id=>1, :name=>"Crear Pagos para Ventas")
Right.create(:id=>2, :name=>"Cambiar Pagos para Ventas")
Right.create(:id=>3, :name=>"Ver Pagos para Ventas")
Right.create(:id=>4, :name=>"Borrar Pagos para Ventas")
Right.create(:id=>5, :name=>"Crear Pagos para Compras")
Right.create(:id=>6, :name=>"Cambiar Pagos para Compras")
Right.create(:id=>7, :name=>"Ver Pagos para Compras")
Right.create(:id=>8, :name=>"Borrar Pagos para Compras")
Right.create(:id=>9, :name=>"Crear Ventas")
Right.create(:id=>10, :name=>"Cambiar Ventas")
Right.create(:id=>11, :name=>"Ver Ventas")
Right.create(:id=>12, :name=>"Borrar Ventas")
Right.create(:id=>13, :name=>"Crear Compras")
Right.create(:id=>14, :name=>"Cambiar Compras")
Right.create(:id=>15, :name=>"Ver Compras")
Right.create(:id=>16, :name=>"Borrar Compras")
Right.create(:id=>17, :name=>"Crear Consumidor Final")
Right.create(:id=>18, :name=>"Cambiar Consumidor Final")
Right.create(:id=>19, :name=>"Ver Consumidor Final")
Right.create(:id=>20, :name=>"Borrar Consumidor Final")
Right.create(:id=>21, :name=>"Crear Credito Fiscal")
Right.create(:id=>22, :name=>"Cambiar Credito Fiscal")
Right.create(:id=>23, :name=>"Ver Credito Fiscal")
Right.create(:id=>24, :name=>"Borrar Credito Fiscal")
Right.create(:id=>25, :name=>"Crear Productos")
Right.create(:id=>26, :name=>"Cambiar Productos")
Right.create(:id=>27, :name=>"Ver Productos")
Right.create(:id=>28, :name=>"Borrar Productos")
Right.create(:id=>29, :name=>"Crear Suscripciones")
Right.create(:id=>30, :name=>"Cambiar Suscripciones")
Right.create(:id=>31, :name=>"Ver Suscripciones")
Right.create(:id=>32, :name=>"Borrar Suscripciones")
Right.create(:id=>33, :name=>"Crear Papeles")
Right.create(:id=>34, :name=>"Cambiar Papeles")
Right.create(:id=>35, :name=>"Ver Papeles")
Right.create(:id=>36, :name=>"Borrar Papeles")
Right.create(:id=>37, :name=>"Crear Usuarios")
Right.create(:id=>38, :name=>"Cambiar Usuarios")
Right.create(:id=>39, :name=>"Ver Usuarios")
Right.create(:id=>40, :name=>"Borrar Usuarios")
Right.create(:id=>41, :name=>"Crear Sitios")
Right.create(:id=>42, :name=>"Cambiar Sitios")
Right.create(:id=>43, :name=>"Ver Sitios")
Right.create(:id=>44, :name=>"Borrar Sitios")
Right.create(:id=>45, :name=>"Crear Cuentas Fisicas")
Right.create(:id=>46, :name=>"Cambiar Cuentas Fisicas")
Right.create(:id=>47, :name=>"Ver Cuentas Fisicas")
Right.create(:id=>48, :name=>"Borrar Cuentas Fisicas")
Right.create(:id=>49, :name=>"Ver COSTS")
Right.create(:id=>50, :name=>"Crear Cuentas")
Right.create(:id=>51, :name=>"Cambiar Cuentas")
Right.create(:id=>52, :name=>"Ver Cuentas")
Right.create(:id=>53, :name=>"Borrar Cuentas")
Right.create(:id=>54, :name=>"Crear Servicios")
Right.create(:id=>55, :name=>"Cambiar Servicios")
Right.create(:id=>56, :name=>"Ver Servicios")
Right.create(:id=>57, :name=>"Borrar Servicios")
Right.create(:id=>58, :name=>"Crear Combos")
Right.create(:id=>59, :name=>"Cambiar Combos")
Right.create(:id=>60, :name=>"Ver Combos")
Right.create(:id=>61, :name=>"Borrar Combos")
Right.create(:id=>62, :name=>"Crear Descuentos")
Right.create(:id=>63, :name=>"Cambiar Descuentos")
Right.create(:id=>64, :name=>"Ver Descuentos")
Right.create(:id=>65, :name=>"Borrar Descuentos")
Right.create(:id=>66, :name=>"Crear Garantias")
Right.create(:id=>67, :name=>"Cambiar Garantias")
Right.create(:id=>68, :name=>"Ver Garantias")
Right.create(:id=>69, :name=>"Borrar Garantias")
Right.create(:id=>70, :name=>"Crear Consumos Internos")
Right.create(:id=>71, :name=>"Cambiar Consumos Internos")
Right.create(:id=>72, :name=>"Ver Consumos Internos")
Right.create(:id=>73, :name=>"Borrar Consumos Internos")
Right.create(:id=>74, :name=>"Crear Numeros de Serie")
Right.create(:id=>75, :name=>"Cambiar Numeros de Serie")
Right.create(:id=>76, :name=>"Ver Numeros de Serie")
Right.create(:id=>77, :name=>"Borrar Numeros de Serie")
Right.create(:id=>78, :name=>"Cambiar Prices")
Right.create(:id=>79, :name=>"Crear Proveedores")
Right.create(:id=>80, :name=>"Cambiar Proveedores")
Right.create(:id=>81, :name=>"Ver Proveedores")
Right.create(:id=>82, :name=>"Borrar Proveedores")
Right.create(:id=>83, :name=>"Crear Transacciones")
Right.create(:id=>84, :name=>"Cambiar Transacciones")
Right.create(:id=>85, :name=>"Ver Transacciones")
Right.create(:id=>86, :name=>"Borrar Transacciones")
Right.create(:id=>87, :name=>"Procesar Cuentas Fisicas")
Right.create(:id=>88, :name=>"Crear Ordenes de Produccion")
Right.create(:id=>89, :name=>"Cambiar Ordenes de Produccion")
Right.create(:id=>90, :name=>"Ver Ordenes de Produccion")
Right.create(:id=>91, :name=>"Borrar Ordenes de Produccion")
Right.create(:id=>92, :name=>"Crear Procesos de Produccion")
Right.create(:id=>93, :name=>"Cambiar Procesos de Produccion")
Right.create(:id=>94, :name=>"Ver Procesos de Produccion")
Right.create(:id=>95, :name=>"Borrar Procesos de Produccion")
Right.create(:id=>96, :name=>"Iniciar Ordenes de Produccion")
Right.create(:id=>97, :name=>"Terminar Ordenes de Produccion")

