# Jade Inventory Control System
#Copyright (C) 2009  Jared T. Martin

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class Right < ActiveRecord::Base
	has_many :rights_roles
	has_many :roles, :through => :rights_roles
	CREATE_PAYMENTS_FOR_SALES = 1
	EDIT_PAYMENTS_FOR_SALES = 2
	VIEW_PAYMENTS_FOR_SALES = 3
	DELETE_PAYMENTS_FOR_SALES = 4
	CREATE_PAYMENTS_FOR_PURCHASES = 5
	EDIT_PAYMENTS_FOR_PURCHASES = 6
	VIEW_PAYMENTS_FOR_PURCHASES = 7
	DELETE_PAYMENTS_FOR_PURCHASES = 8
	CREATE_SALES = 9
	EDIT_SALES = 10
	VIEW_SALES = 11
	DELETE_SALES = 12
	CREATE_PURCHASES = 13
	EDIT_PURCHASES = 14
	VIEW_PURCHASES = 15
	DELETE_PURCHASES = 16
	CREATE_INDIVIDUAL_CLIENTS = 17
	EDIT_INDIVIDUAL_CLIENTS = 18
	VIEW_INDIVIDUAL_CLIENTS = 19
	DELETE_INDIVIDUAL_CLIENTS = 20
	CREATE_ORGANIZATION_CLIENTS = 21
	EDIT_ORGANIZATION_CLIENTS = 22
	VIEW_ORGANIZATION_CLIENTS = 23
	DELETE_ORGANIZATION_CLIENTS = 24
	CREATE_PRODUCTS = 25
	EDIT_PRODUCTS = 26
	VIEW_PRODUCTS = 27
	DELETE_PRODUCTS = 28
	CREATE_SUBSCRIPTIONS = 29
	EDIT_SUBSCRIPTIONS = 30
	VIEW_SUBSCRIPTIONS = 31
	DELETE_SUBSCRIPTIONS = 32
	CREATE_ROLES = 33
	EDIT_ROLES = 34
	VIEW_ROLES = 35
	DELETE_ROLES = 36
	CREATE_USERS = 37
	EDIT_USERS = 38
	VIEW_USERS = 39
	DELETE_USERS = 40	
	CREATE_SITES = 41
	EDIT_SITES = 42
	VIEW_SITES = 43
	DELETE_SITES = 44	
	CREATE_PHYSICAL_COUNTS = 45
	EDIT_PHYSICAL_COUNTS = 46
	VIEW_PHYSICAL_COUNTS = 47
	DELETE_PHYSICAL_COUNTS = 48	
	VIEW_COSTS = 49
	CREATE_ACCOUNTS =50
	EDIT_ACCOUNTS =51
	VIEW_ACCOUNTS =52
	DELETE_ACCOUNTS =53
	CREATE_SERVICES =54
	EDIT_SERVICES =55
	VIEW_SERVICES =56
	DELETE_SERVICES =57
	CREATE_COMBOS =58
	EDIT_COMBOS =59
	VIEW_COMBOS =60
	DELETE_COMBOS =61
	CREATE_DISCOUNTS =62
	EDIT_DISCOUNTS =63
	VIEW_DISCOUNTS =64
	DELETE_DISCOUNTS =65
	CREATE_WARRANTIES =66
	EDIT_WARRANTIES =67
	VIEW_WARRANTIES =68
	DELETE_WARRANTIES =69
	CREATE_INTERNAL_CONSUMPTIONS =70
	EDIT_INTERNAL_CONSUMPTIONS =71
	VIEW_INTERNAL_CONSUMPTIONS =72
	DELETE_INTERNAL_CONSUMPTIONS =73
	CREATE_SERIALS =74
	EDIT_SERIALS =75
	VIEW_SERIALS =76
	DELETE_SERIALS =77
	EDIT_PRICES =78
	CREATE_VENDORS =79
	EDIT_VENDORS =80
	VIEW_VENDORS =81
	DELETE_VENDORS =82
	CREATE_TRANSACTIONS=83
	CHANGE_TRANSACTIONS=84
	VIEW_TRANSACTIONS=85
	DELETE_TRANSACTIONS=86
	POST_COUNTS=87
	
	
end
